# Generated by Django 4.2.21 on 2025-05-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="cancelled_on",
            field=models.DateField(auto_now=True),
        ),
    ]
