# Generated by Django 4.2.21 on 2025-05-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_subscription_cancelled_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="billing.subscription",
            ),
        ),
    ]
